"""initial_schema

Revision ID: aeeeb0e464a9
Revises: 
Create Date: 2026-09-24 07:38:57.449627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeeeb0e464a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classroom_code', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('economy_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_economy_events_player_tick', 'economy_events', ['player_id', 'tick'], unique=False)
    op.create_table('player_economy',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('wallet', sa.Float(), nullable=True),
    sa.Column('savings_goal', sa.Float(), nullable=True),
    sa.Column('savings_emergency', sa.Float(), nullable=True),
    sa.Column('savings_free', sa.Float(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('job_performance', sa.Float(), nullable=True),
    sa.Column('wage_per_period', sa.Float(), nullable=True),
    sa.Column('loans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Float(), nullable=True),
    sa.Column('current_tick', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('goal_item', sa.String(), nullable=True),
    sa.Column('goal_target', sa.Float(), nullable=True),
    sa.Column('goal_saved', sa.Float(), nullable=True),
    sa.Column('inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_economy')
    op.drop_index('ix_economy_events_player_tick', table_name='economy_events')
    op.drop_table('economy_events')
    op.drop_table('users')
    # ### end Alembic commands ###
